version: 2.3.4.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2204
install:
- sh: >-
    sudo apt-get update

    sudo apt-get --assume-yes install libgnutls28-dev
build_script:
- sh: >-
    cd src/Release

    CC=gcc make fftp
    
